version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"    # maps host port 3000 to container's port 80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
